version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:8080"
    env_file:
      - .env_file
    environment:
      - FLASK_APP=main.py
    # depends_on:
    #   - db
    volumes:
      - .:/app # copies container folder to locally
  # db:
  #   image: postgres:13-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=fyyur
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"

  # pg-admin:
  #   image: dpage/pgadmin4:6
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@email.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #     - PGADMIN_LISTEN_PORT=5050
  # 
  #   ports:
  #     - "5050:5050"

volumes:
  postgres_data:
